FROM python:3.12-slim

RUN apt-get update && apt-get install -y git libenchant-2-2 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . ./agents/

RUN mkdir -p /app/tempCloned
RUN chmod +x /app/agents/entrypoint.sh
ENV PYTHONPATH=/app/agents
ENTRYPOINT ["/app/agents/entrypoint.sh"]
