import sys  #For reading command-line arguments
import json #For JSON serialization
import time #For simulating delays

def main():
    if len(sys.argv) < 2:
        print(json.dumps({"error": "No URL provided"}))
        sys.exit(1)

    repo_url = sys.argv[1]

    print(f"DEBUG: Orchestrator started for {repo_url}", file=sys.stderr)
    
    # Simulate agents waiting
    time.sleep(1.5)
    print("DEBUG: Reviewer agent finished analysis", file=sys.stderr)
    # Final result (Mock)
    mock_response = {
        "status": "success",
        "repo": repo_url,
        "results": {
            "reviewer": {
                "files_scanned": 5,
                "typos": [
                    {"file": "README.md", "word": "errorr", "suggestion": "error"}
                ]
            }
        },
        "note": "This is an output generated by the real Python orchestrator (but with fake data)."
    }

    print(json.dumps(mock_response))

if __name__ == "__main__":
    main()